/*
 * ORY Hydra - Cloud Native OAuth 2.0 and OpenID Connect Server
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here. Keep in mind that this document reflects the latest branch, always. Support for versioned documentation is coming in the future.
 *
 * OpenAPI spec version: Latest
 * Contact: hi@ory.am
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.KeyGenerator;
import io.swagger.client.model.Manager;
import io.swagger.client.model.Writer;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Handler
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-07-10T19:14:58.181+02:00")
public class Handler {
  @SerializedName("Generators")
  private Map<String, KeyGenerator> generators = null;

  @SerializedName("H")
  private Writer H = null;

  @SerializedName("Manager")
  private Manager manager = null;

  public Handler generators(Map<String, KeyGenerator> generators) {
    this.generators = generators;
    return this;
  }

  public Handler putGeneratorsItem(String key, KeyGenerator generatorsItem) {
    if (this.generators == null) {
      this.generators = new HashMap<String, KeyGenerator>();
    }
    this.generators.put(key, generatorsItem);
    return this;
  }

   /**
   * Get generators
   * @return generators
  **/
  @ApiModelProperty(value = "")
  public Map<String, KeyGenerator> getGenerators() {
    return generators;
  }

  public void setGenerators(Map<String, KeyGenerator> generators) {
    this.generators = generators;
  }

  public Handler H(Writer H) {
    this.H = H;
    return this;
  }

   /**
   * Get H
   * @return H
  **/
  @ApiModelProperty(value = "")
  public Writer getH() {
    return H;
  }

  public void setH(Writer H) {
    this.H = H;
  }

  public Handler manager(Manager manager) {
    this.manager = manager;
    return this;
  }

   /**
   * Get manager
   * @return manager
  **/
  @ApiModelProperty(value = "")
  public Manager getManager() {
    return manager;
  }

  public void setManager(Manager manager) {
    this.manager = manager;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Handler handler = (Handler) o;
    return Objects.equals(this.generators, handler.generators) &&
        Objects.equals(this.H, handler.H) &&
        Objects.equals(this.manager, handler.manager);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generators, H, manager);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Handler {\n");
    
    sb.append("    generators: ").append(toIndentedString(generators)).append("\n");
    sb.append("    H: ").append(toIndentedString(H)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

